### PR TITLE
Build using GitHub action

### PR DESCRIPTION
**Pull request by jburel**
Build using GitHub action
This is the initial step to build using actions. 
Other change will be required to add support for repository dispatch (bf2raw is used in https://github.com/ome/ome_zarr_test_suite)
This will be done in a follow up PR 

cc @joshmoore

### CODE REVIEW

**Comment by jburel** [comment]
successful run https://github.com/jburel/bioformats2raw/actions/runs/1159466128

**Comment by joshmoore** [comment]
And events can propagate across organizations?

**Comment by jburel** [comment]
I have not tested that yet.

**Comment by jburel** [comment]
I tested using my account https://github.com/jburel/ome_zarr_test_suite/runs/3412494804. This was triggered from the fork of bf2raw

**Comment by jburel** [comment]
and the correct tests were run
```
test_suite.py::test[create-info] SKIPPED (skip set: True)                [  3%]
test_suite.py::test[create-downloads] SKIPPED (skip set: True)           [  7%]
test_suite.py::test[create-checksum] SKIPPED (skip set: True)            [ 10%]
test_suite.py::test[localfake1-info] SKIPPED (skip set: True)            [ 14%]
test_suite.py::test[localfake1-downloads] SKIPPED (skip set: True)       [ 17%]
test_suite.py::test[localfake1-checksum] SKIPPED (skip set: True)        [ 21%]
test_suite.py::test[localfake2-info] SKIPPED (skip set: True)            [ 25%]
test_suite.py::test[localfake2-downloads] SKIPPED (skip set: True)       [ 28%]
test_suite.py::test[localfake2-checksum] SKIPPED (skip set: True)        [ 32%]
test_suite.py::test[localfake3-info] SKIPPED (skip set: True)            [ 35%]
test_suite.py::test[localfake3-downloads] SKIPPED (skip set: True)       [ 39%]
test_suite.py::test[localfake3-checksum] SKIPPED (skip set: True)        [ 42%]
test_suite.py::test[remotefake1-info] SKIPPED (skip set: True)           [ 46%]
test_suite.py::test[remotefake1-downloads] SKIPPED (skip set: True)      [ 50%]
test_suite.py::test[remotefake1-checksum] SKIPPED (skip set: True)       [ 53%]
test_suite.py::test[remotefake2-info] SKIPPED (skip set: True)           [ 57%]
test_suite.py::test[remotefake2-downloads] SKIPPED (skip set: True)      [ 60%]
test_suite.py::test[remotefake2-checksum] SKIPPED (skip set: True)       [ 64%]
test_suite.py::test[idr6001240-info] SKIPPED (skip set: True)            [ 67%]
test_suite.py::test[idr6001240-downloads] SKIPPED (skip set: True)       [ 71%]
test_suite.py::test[idr6001240-checksum] SKIPPED (skip set: True)        [ 75%]
test_suite.py::test[bf2rawraw-info] PASSED                               [ 78%]
test_suite.py::test[bf2rawraw-downloads] PASSED                          [ 82%]
test_suite.py::test[bf2rawraw-checksum] PASSED                           [ 85%]
test_suite.py::test[bf2rawcompressed-info] PASSED                        [ 89%]
test_suite.py::test[bf2rawcompressed-downloads] PASSED                   [ 92%]
test_suite.py::test[bf2rawcompressed-checksum] PASSED                    [ 96%]
test_suite.py::test_all_scripts_used PASSED                              [100%]
```

**Pull request merged**
