### PR TITLE
Use OpenCV to downsample resolutions

### LINKED ISSUE #52: 32 Bit IMS-MALDI Low Resolutions Looking Odd
Hello,

We are running the `bioformats2raw` -> `raw2ometiff` pipeline on some imaging mass spectrometry data that is 32 bit float data.  The data can sometimes be "sparse" and we see some weird artifacts in the lower resolutions of the pyramid.  There are some "stripes" that appear only on lower resolutions:
Screen Shot 2020-07-20 at 1 18 38 PM

Screen Shot 2020-07-20 at 1 19 45 PM

Here is the pyramid and original:
original: https://storage.googleapis.com/vitessce-demo-data/test-data/hubmap/test/ims_compressed_no_pyramid/VAN0012-RK-103-75-IMS_NegMode_multilayer.ome.tif
pyramid: https://storage.googleapis.com/vitessce-demo-data/test-data/hubmap/test/ims_compressed_pyramid/VAN0012-RK-103-75-IMS_NegMode_multilayer.ome.tif

Thanks! If you need more examples, we have a few.

### PR DESCRIPTION
**Pull request by melissalinkert**
Automatically includes Gaussian blurring, which fixes #52.

### CODE REVIEW

**Comment by joshmoore** [comment]
I'd imagine we could use this opportunity to add exemplary metadata to https://github.com/glencoesoftware/bioformats2raw/blob/69d6dc65b50368e6d760e309e8058186d531df5e/src/main/java/com/glencoesoftware/bioformats2raw/Converter.java#L1064 roughly of the form:

```
      "metadata": {
        "method": "org.opencv.imgproc.Imgproc.pyrDown",
        "version": "3.4.2-1", // Too much of a pain?
```

**Comment by chris-allan** [comment]
Very easy to get the OpenCV version string from `org.opencv.core.Core.VERSION`

**Comment by ngehlenborg** [comment]
Do you have an approximate timeline for when this will make it into a release? We are considering to reprocess some data for the first HuBMAP release if the issue discussed in #52 can indeed be resolved by these changes. Thanks!

**Comment by joshmoore** [comment]
Sorry for having derailed things, @ngehlenborg. I've opened https://github.com/melissalinkert/bioformats2raw/pull/1 for @melissalinkert's review, but happy to see that added later if need be.

Example:

```
bioformats2raw/build/distributions $cat a.out/data.n5/0/attributes.json  | jq
{
  "multiscales": [
    {
      "metadata": {
        "method": "org.opencv.imgproc.Imgproc.pyrDown",
        "version": "3.4.2"
      },
      "type": "gaussian",
      "datasets": [
        {
          "path": "0"
        },
        {
          "path": "1"
        }
      ],
      "version": "0.1"
    }
  ]
}
```

**Comment by chris-allan** [comment]
@ngehlenborg: Not for at least a week. At a minimum the concepts here need to be made optional and configurable; not everyone wants this style of downsampling. Also, teammembers who need to review these PRs will be out of office next week.

If this PR does exactly what you want and you don't want to build your own, artifacts are always available from the AppVeyor CI builds. The latest one as of this writing is here:

 * https://ci.appveyor.com/project/gs-jenkins/bioformats2raw/builds/34664742

**Comment by ngehlenborg** [comment]
Thanks @chris-allan, we will take a look at the latest builds to see if these changes address our problem.

**Comment by ngehlenborg** [comment]
Just a heads up that the new downsampling options allowed us to address the issue described in #52. Gaussian turned out to be too blurry, but cubic interpolation worked very well. We will put up a demo showing the different options once the HuBMAP data has been officially released.

**Pull request merged**
