### PR TITLE
Resolution-based progress bars

### PR DESCRIPTION
**Pull request by joshmoore**
Uses http://tongfei.me/progressbar/ to print progress
bars for each resolution to standard out. The default
logging level is set to WARN for optimal display when
there are no issues.

```
$ build/install/bioformats2raw/bin/bioformats2raw build/install/a.fake build/out
resolution 0 100% │█████████████████████████████████████████████████████████████████████████│ 2400/2400 (0:00:05 / 0:00:00)
resolution 1 100% │███████████████████████████████████████████████████████████████████████████│ 600/600 (0:00:03 / 0:00:00)
resolution 2 100% │███████████████████████████████████████████████████████████████████████████│ 150/150 (0:00:00 / 0:00:00)
resolution 3 100% │███████████████████████████████████████████████████████████████████████████│ 150/150 (0:00:00 / 0:00:00)
resolution 4 100% │███████████████████████████████████████████████████████████████████████████│ 150/150 (0:00:00 / 0:00:00)
```

### CODE REVIEW

**Comment by joshmoore** [comment]
A weekend suggestion. Feel free to close, or I can place this behind a command-line option if preferred.

**Comment by joshmoore** [comment]
https://user-images.githubusercontent.com/88113/109393849-4f3b4500-7924-11eb-9bef-d914b1027ec2.mp4

**Comment by melissalinkert** [comment]
Very cool.  I don't know that a separate option is necessary, but maybe just turn off the progress bars if the log level is changed from ```WARN```?

**Comment by joshmoore** [comment]
Good idea. Implemented:

```
(base) /opt/bioformats2raw $build/install/bioformats2raw/bin/bioformats2raw a.fake build/log2 --log-level=INFO
2021-03-01 18:04:41,834 [main] INFO  loci.formats.ImageReader - FakeReader initializing a.fake
2021-03-01 18:04:42,013 [main] INFO  c.g.bioformats2raw.Converter - Using 2 pyramid resolutions
2021-03-01 18:04:42,013 [main] INFO  c.g.bioformats2raw.Converter - Preparing to write pyramid sizeX 512 (tileWidth: 1024) sizeY 512 (tileWidth: 1024) imageCount 1
2021-03-01 18:04:42,132 [main] INFO  c.g.bioformats2raw.Converter - Reducing active tileWidth to 512
2021-03-01 18:04:42,132 [main] INFO  c.g.bioformats2raw.Converter - Reducing active tileHeight to 512
2021-03-01 18:04:42,237 [ProgressBar] INFO  c.g.bioformats2raw.Converter - [0/0]   0% │                                                                                              │ 0/1 (0:00:00 / ?)
2021-03-01 18:04:42,274 [pool-1-thread-1] INFO  c.g.bioformats2raw.Converter - requesting tile to write at [0, 0, 0, 0, 0] to 0/0
2021-03-01 18:04:42,284 [pool-1-thread-1] INFO  c.g.bioformats2raw.Converter - tile read complete 1/1
2021-03-01 18:04:42,285 [pool-1-thread-1] INFO  org.perf4j.TimingLogger - start[1614618282274] time[10] tag[getTile]
2021-03-01 18:04:42,371 [pool-1-thread-1] INFO  c.g.bioformats2raw.Converter - Successfully processed tile; resolution=0 plane=0 xx=0 yy=0 width=512 height=512
2021-03-01 18:04:42,372 [ProgressBar] INFO  c.g.bioformats2raw.Converter - [0/0] 100% │████████████████████████████████████████████████████████████████████████████████████████│ 1/1 (0:00:00 / 0:00:00)
2021-03-01 18:04:42,379 [main] INFO  c.g.bioformats2raw.Converter - Reducing active tileWidth to 256
2021-03-01 18:04:42,379 [main] INFO  c.g.bioformats2raw.Converter - Reducing active tileHeight to 256
2021-03-01 18:04:42,401 [ProgressBar] INFO  c.g.bioformats2raw.Converter - [0/1]   0% │                                                                                              │ 0/1 (0:00:00 / ?)
2021-03-01 18:04:42,402 [pool-1-thread-2] INFO  c.g.bioformats2raw.Converter - requesting tile to write at [0, 0, 0, 0, 0] to 0/1
2021-03-01 18:04:42,408 [pool-1-thread-2] INFO  org.perf4j.TimingLogger - start[1614618282402] time[3] tag[getTileDownsampled]
2021-03-01 18:04:42,408 [pool-1-thread-2] INFO  c.g.bioformats2raw.Converter - tile read complete 1/1
2021-03-01 18:04:42,408 [pool-1-thread-2] INFO  org.perf4j.TimingLogger - start[1614618282402] time[5] tag[getTile]
2021-03-01 18:04:42,408 [pool-1-thread-2] INFO  c.g.bioformats2raw.Converter - Successfully processed tile; resolution=1 plane=0 xx=0 yy=0 width=256 height=256
2021-03-01 18:04:42,409 [ProgressBar] INFO  c.g.bioformats2raw.Converter - [0/1] 100% │████████████████████████████████████████████████████████████████████████████████████████│ 1/1 (0:00:00 / 0:00:00)
```

So the bars make a visual guide to where each section occurs.

Note: also trying out the more concise `[0:0]` notation to start each progress bar. Opinions welcome!

**Comment by melissalinkert** [comment]
That looks fine with a small example, but with something that has more tiles like ```bin/bioformats2raw "test&sizeX=10000&sizeY=10000&sizeZ=3.fake" test --log-level INFO```, partial progress bars are shown multiple times for each resolution. Personally I think it would be clearer to just not show any progress bar if the log level is changed from the default.

**Comment by joshmoore** [comment]
Understood. Any objections to using `LOGGER::trace` in order to keep the code simpler? (Otherwise, I'll need to remove the try/close block.

**Comment by melissalinkert** [comment]
That approach is fine with me; OK to merge from my side unless any objections from @chris-allan.

**Comment by chris-allan** [comment]
Looks great. The default vs. non-default logging stuff just seems confusing to me. Maybe take the rsync et al approach and just give the user the option to turn it on with `-p / --progress`?

**Comment by joshmoore** [comment]
MSTM. And the behavior if progress is not set? Basically sit there quietly like rsync would (unless `-v` or in our case `--log-level` is passed)?

**Comment by chris-allan** [comment]
> MSTM. And the behavior if progress is not set? Basically sit there quietly like rsync would (unless `-v` or in our case `--log-level` is passed)?

Sit there quietly unless `-p` or `--progress` is passed irrespective of whatever log level is passed.

**Comment by joshmoore** [comment]
```
# Default
(base) /opt/bioformats2raw $build/install/bioformats2raw/bin/bioformats2raw a.fake build/_out1
```

```
# Progress bar
(base) /opt/bioformats2raw $build/install/bioformats2raw/bin/bioformats2raw a.fake build/_out2 --progress
[0/0] 100% │██████████████████████████████████████████████████████████████████████████████████████│ 1/1 (0:00:00 / 0:00:00)
[0/1] 100% │██████████████████████████████████████████████████████████████████████████████████████│ 1/1 (0:00:00 / 0:00:00)
```

```
# With more logging
(base) /opt/bioformats2raw $build/install/bioformats2raw/bin/bioformats2raw a.fake build/_out3 --progress --log-level trace
...
2021-03-04 09:37:05,747 [pool-1-thread-1] INFO  c.g.bioformats2raw.Converter - requesting tile to write at [0, 0, 0, 0, 0] to 0/0
2021-03-04 09:37:05,757 [pool-1-thread-1] INFO  c.g.bioformats2raw.Converter - tile read complete 1/1
2021-03-04 09:37:05,757 [pool-1-thread-1] INFO  org.perf4j.TimingLogger - start[1614847025747] time[10] tag[getTile]
2021-03-04 09:37:05,851 [pool-1-thread-1] DEBUG c.g.bioformats2raw.Converter - start[1614847025758] time[92] tag[writeBytes]
2021-03-04 09:37:05,851 [pool-1-thread-1] INFO  c.g.bioformats2raw.Converter - Successfully processed tile; resolution=0 plane=0 xx=0 yy=0 width=512 height=512
2021-03-04 09:37:05,851 [ProgressBar] TRACE c.g.bioformats2raw.Converter - [0/0] 100% │████████████████████████████████████████████████████████████████████████████████████████│ 1/1 (0:00:00 / 0:00:00)
2021-03-04 09:37:05,858 [main] INFO  c.g.bioformats2raw.Converter - Reducing active tileWidth to 256
2021-03-04 09:37:05,859 [main] INFO  c.g.bioformats2raw.Converter - Reducing active tileHeight to 256
2021-03-04 09:37:05,883 [ProgressBar] TRACE c.g.bioformats2raw.Converter - [0/1]   0% │                                                                                              │ 0/1 (0:00:00 / ?)
2021-03-04 09:37:05,884 [pool-1-thread-2] INFO  c.g.bioformats2raw.Converter - requesting tile to write at [0, 0, 0, 0, 0] to 0/1
2021-03-04 09:37:05,887 [pool-1-thread-2] INFO  org.perf4j.TimingLogger - start[1614847025884] time[3] tag[getTileDownsampled]
2021-03-04 09:37:05,888 [pool-1-thread-2] INFO  c.g.bioformats2raw.Converter - tile read complete 1/1
2021-03-04 09:37:05,888 [pool-1-thread-2] INFO  org.perf4j.TimingLogger - start[1614847025884] time[4] tag[getTile]
2021-03-04 09:37:05,888 [pool-1-thread-2] DEBUG c.g.bioformats2raw.Converter - start[1614847025888] time[0] tag[writeBytes]
2021-03-04 09:37:05,888 [pool-1-thread-2] INFO  c.g.bioformats2raw.Converter - Successfully processed tile; resolution=1 plane=0 xx=0 yy=0 width=256 height=256
2021-03-04 09:37:05,888 [ProgressBar] TRACE c.g.bioformats2raw.Converter - [0/1] 100% │████████████████████████████████████████████████████████████████████████████████████████│ 1/1 (0:00:00 / 0:00:00)
(base) /opt/bioformats2raw $
```

**Pull request merged**
